In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('New_Car_Automobile.csv')

In [5]:
data

,car-name,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,10.779306,111.0,5000.0,21,27,13495.0
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,10.779306,111.0,5000.0,21,27,16500.0
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,10.779306,154.0,5000.0,19,26,16500.0
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.000000,102.0,5500.0,24,30,13950.0
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,10.779306,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2045,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.500000,114.0,5400.0,23,28,16845.0
2046,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.700000,160.0,5300.0,19,25,19045.0
2047,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.800000,134.0,5500.0,18,23,21485.0
2048,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.000000,106.0,4800.0,26,27,22470.0
2049,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.500000,114.0,5400.0,19,25,22625.0

In [6]:
data['car-name'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [8]:
data['car-name'].value_counts()

toyota           320
nissan           180
mazda            170
honda            130
mitsubishi       130
subaru           120
volkswagen       120
volvo            110
peugot           110
dodge             90
mercedes-benz     80
bmw               80
plymouth          70
audi              70
saab              60
porsche           50
isuzu             40
chevrolet         30
jaguar            30
alfa-romero       30
renault           20
mercury           10
Name: car-name, dtype: int64

In [10]:
# loading the input variables in x excluding the class column as it is output
x=data.drop('car-name',axis=1)

In [11]:
x

,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,130,mpfi,3.47,2.68,10.779306,111.0,5000.0,21,27,13495.0
1,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,130,mpfi,3.47,2.68,10.779306,111.0,5000.0,21,27,16500.0
2,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,152,mpfi,2.68,3.47,10.779306,154.0,5000.0,19,26,16500.0
3,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,...,109,mpfi,3.19,3.40,10.000000,102.0,5500.0,24,30,13950.0
4,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,...,136,mpfi,3.19,3.40,10.779306,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2045,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,141,mpfi,3.78,3.15,9.500000,114.0,5400.0,23,28,16845.0
2046,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,...,141,mpfi,3.78,3.15,8.700000,160.0,5300.0,19,25,19045.0
2047,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,173,mpfi,3.58,2.87,8.800000,134.0,5500.0,18,23,21485.0
2048,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,145,idi,3.01,3.40,23.000000,106.0,4800.0,26,27,22470.0
2049,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,141,mpfi,3.78,3.15,9.500000,114.0,5400.0,19,25,22625.0

In [12]:
y=data[['car-name']]

In [13]:
y

         car-name
0     alfa-romero
1     alfa-romero
2     alfa-romero
3            audi
4            audi
...           ...
2045        volvo
2046        volvo
2047        volvo
2048        volvo
2049        volvo

[2050 rows x 1 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le=LabelEncoder()

In [16]:
x[['fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system']]=x[['fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system']].apply(le.fit_transform)

In [17]:
x

,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,1,0,1,0,2,0,88.6,168.8,64.1,48.8,...,130,5,3.47,2.68,10.779306,111.0,5000.0,21,27,13495.0
1,1,0,1,0,2,0,88.6,168.8,64.1,48.8,...,130,5,3.47,2.68,10.779306,111.0,5000.0,21,27,16500.0
2,1,0,1,2,2,0,94.5,171.2,65.5,52.4,...,152,5,2.68,3.47,10.779306,154.0,5000.0,19,26,16500.0
3,1,0,0,3,1,0,99.8,176.6,66.2,54.3,...,109,5,3.19,3.40,10.000000,102.0,5500.0,24,30,13950.0
4,1,0,0,3,0,0,99.4,176.6,66.4,54.3,...,136,5,3.19,3.40,10.779306,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2045,1,0,0,3,2,0,109.1,188.8,68.9,55.5,...,141,5,3.78,3.15,9.500000,114.0,5400.0,23,28,16845.0
2046,1,1,0,3,2,0,109.1,188.8,68.8,55.5,...,141,5,3.78,3.15,8.700000,160.0,5300.0,19,25,19045.0
2047,1,0,0,3,2,0,109.1,188.8,68.9,55.5,...,173,5,3.58,2.87,8.800000,134.0,5500.0,18,23,21485.0
2048,0,1,0,3,2,0,109.1,188.8,68.9,55.5,...,145,3,3.01,3.40,23.000000,106.0,4800.0,26,27,22470.0
2049,1,1,0,3,2,0,109.1,188.8,68.9,55.5,...,141,5,3.78,3.15,9.500000,114.0,5400.0,19,25,22625.0

In [18]:
y=le.fit_transform(y)

C:\Users\USER\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [19]:
y

array([ 0,  0,  0, ..., 21, 21, 21])

In [20]:
# Importing the model
from sklearn.tree import DecisionTreeClassifier

In [21]:
# Creating the object
dtc = DecisionTreeClassifier(criterion='entropy')     #by default it takes gini

In [22]:
# Train the model using fit function
dtc.fit(x,y)

DecisionTreeClassifier(criterion='entropy')

In [23]:
# prredict on x dataset
y_pred = dtc.predict(x)

In [24]:
y_pred

array([ 0,  0,  0, ..., 21, 21, 21])

In [25]:
y

array([ 0,  0,  0, ..., 21, 21, 21])

In [27]:
from sklearn.metrics import classification_report,accuracy_score

In [28]:
csr = classification_report(y,y_pred)

In [30]:
print(csr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        70
           2       1.00      1.00      1.00        80
           3       1.00      1.00      1.00        30
           4       0.90      1.00      0.95        90
           5       1.00      1.00      1.00       130
           6       1.00      1.00      1.00        40
           7       1.00      1.00      1.00        30
           8       1.00      1.00      1.00       170
           9       1.00      1.00      1.00        80
          10       1.00      1.00      1.00        10
          11       1.00      1.00      1.00       130
          12       1.00      1.00      1.00       180
          13       1.00      1.00      1.00       110
          14       1.00      0.86      0.92        70
          15       1.00      1.00      1.00        50
          16       1.00      1.00      1.00        20
          17       1.00      1.00      1.00        60
          18       1.00      1.00      1.00       120
          19       1.00      1.00      1.00       320
          20       1.00      1.00      1.00       120
          21       1.00      1.00      1.00       110

    accuracy                           1.00      2050
   macro avg       1.00      0.99      0.99      2050
weighted avg       1.00      1.00      1.00      2050

In [31]:
acc = accuracy_score(y,y_pred)

In [32]:
acc

0.9951219512195122